--- #YAML:1.0
name:                Compress-unLZMA
version:             0.02
abstract:            Interface to LZMA decompression library
license:             ~
author:              
    - Fabien POTENCIER <fabpot@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
